<header>
  <div id="topheader">
<nav class="navbar navbar-expand-md navbar-dark fixed-top">
      <a class="navbar-brand" href="#">
      <img src="/images/Logo_Feedback_small.png" alt="Feedback Logo" style="width:50px;">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="/index.html">Home</a>
          </li>
<!--
          <li class="nav-item">
            <a class="nav-link" href="/news.html">News</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/projects.html">Projects</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/documents.html">Documents</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Data</a>
          </li>
-->
          <li class="nav-item dropdown">
           <a class="nav-link dropdown-toggle" href="#" id="toolsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Tools</a>
             <div class="dropdown-menu" aria-labelledby="toolsDropdown">
                  <a class="dropdown-item" href="http://dustem.astro.umd.edu" target="_blank">PDR Toolbox</a>
             </div>
          </li>
          <li class="nav-item dropdown">
           <a class="nav-link dropdown-toggle" href="#" id="teamDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Team</a>
             <div class="dropdown-menu" aria-labelledby="teamDropdown">
                  <a class="dropdown-item" href="team.html">Meet The Science Team</a>
            <a class="dropdown-item" href="https://wiki.astro.uni-koeln.de/wikis/!feedbacklegacyproject" target="_blank">Team Wiki</a>
            <a class="dropdown-item" href="https://astro.uni-koeln.de/18130.html" target="_blank">Univ. of Koeln FEEDBACK</a>
             </div>
          </li>
          <li class="nav-item dropdown">
           <a class="nav-link dropdown-toggle" href="#" id="aboutDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          About</a>
             <div class="dropdown-menu" aria-labelledby="aboutDropdown">
                  <a class="dropdown-item" href="about.html">The FEEDBACK Project</a>
                  <a class="dropdown-item" href="https://www.sofia.usra.edu" target="_blank">SOFIA</a>
             </div>
          </li>

<!--
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
-->
        </ul>
<!--
        <form class="form-inline mt-2 mt-md-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
-->
      </div>
    </nav>

  </div>
</header>
